# -*- coding: utf-8 -*-
"""day4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IVCzOz2d80PMmD9bXmaHHX1LLtiBAgsU
"""



"""DATA STRUCTURE

LISTS
"""

a = [1,2,3,4,5,6,7]
print(a)

b = [1,2,3,'raju']
print(b)

"""LIST OPERATION"""

print(a[0])#output: 1
print(b[-1])#output:5

"""MODIFYING ITEMS"""

a[0] = 10
print(a) # output:[10,2,3,4,5]

"""ADDING ITEMS"""

a.append(6)
a

"""INSERT()"""

a.insert(1,15)
a

"""REMOVING ITEM

REMOVE()
"""

b.remove(2)
b

"""POP()"""

a.pop(2)
a

"""ADDING ITEMS"""

a=[1,2,3,4,5]
a.append(6)
print(a)
a=[1,2,3,4,5]
a.insert(1,15)
print(a)
a = [1,2,3,4,5]
a.remove(2)
print(a)

a = ["nammu"]
len(a)
a = [1,2,3,4,5]
a.sort()
print(a)
a = [1,2,3,4,5]
a.reverse()
a

"""TUPLES"""

a = (10,20,30)
a

"""ACEESSING ITEMS IN A TUPLE"""

print(coordinates[0])

"""accessing"""

print(student["name"])

"""sets"""

numbers = {1,2,3,4,5}
print(a)

"""HANDS ON PRACTICE

1.MANUPULATING LISTS
"""

fruits = ["apple","banana","cherry"]
fruits.append("orange")
fruits.remove("banana")
print(fruits)

"""CREATING A DICTIONARY"""

book = {"title":"python basics",
        "author":"john doe",
        "year":2021}
print(book["title"])
book["year"]=2022
print(book)

"""WORKING WITH SETS"""

set1 = {1,2,3,4}
set2 = {3,4,5,6}
print("union:",set1|set2)
print("intersection:",set1 & set2)
print("difference:",set1 - set2)

"""16] MERGE TWO LISTS"""

list1 =[1,2,3]
list2 =[4,5,6]
merged_list = list1 + list2
print("merged list:",merged_list)

"""17]  DICTIONARY OPERATIONS"""

student = {"name":"john","age":21,"marks":85}
print("name:",student["name"])
student["marks"] =90
print("updates marks:",student["marks"])

"""18] FIND THE MAXIMUM AND MINIMUM IN A LIST"""

numbers = [10,20,30,40,50]
print("Maximum:", max(numbers))
print("Minimum:", min(numbers))

"""19]  COUNT FREQUENCY OF ELEMENTS IN A LIST

"""

numbers = [1,2,3,3,3,4,4,4,4]
frequency = {}
for num in numbers:
  frequency[num] = frequency.get(num,0) + 1
print("frequency of elements:",frequency)

"""20]  SORT A LIST OF TUPLES BY THE SECOND ELEMENTS"""

tuples =[(1,'apple'),(2,'banana'),(3,'cherry')]
sorted_tuples = sorted(tuples,key=lambda x:x[1])
print("sorted tuples:", sorted_tuples)

"""DICTIONARY"""

student={"name": "megha","age":18, "colour": "white"}
print(student)
print(student["name"])
print(student[ 'colour'])
print(student["age"])

student["age"]=15
student

#adding

student['grade']="A"
student

""" #important
PALIDROME
"""

number = int(input("enter a number:"))
reverse_number = 0
temp = number

while temp> 0:
  digit = temp % 10
  reverse_number = reverse_number * 10 + digit
  temp = temp// 10

if number == reverse_number:
    print(f" {number}pali")
else:
  print(f"{number} not pali")

number = input("enter a number: ")
if number == number[::-1]:
  print("palidrome")
else:
  print("not palidrome")